version: 0.2

#env:
  #variables:
  #parameter-store:
     # key: "value"
     # key: "value"
  #secrets-manager:
     # key: secret-id:json-key:version-stage:version-id
     # key: secret-id:json-key:version-stage:version-id
  #exported-variables:
     # - variable
     # - variable
  #git-credential-helper: yes
#batch:
  #fast-fail: true
  #build-list:
  #build-matrix:
  #build-graph:
phases:
  install:
    #If you use the Ubuntu standard image 2.0 or later, you must specify runtime-versions.
    #If you specify runtime-versions and use an image other than Ubuntu standard image 2.0, the build fails.
    #runtime-versions:
      # name: version
      # name: version
    commands:
      - node -v
      - echo npm -v
      - npm -v
      - yarn -v
  pre_build:
    commands:
      - chmod +x scripts/post-build.sh
      - chmod +x scripts/trim-node-modules.sh
      - npx create-strapi-app kor-strapi --dbclient=postgres --dbport=5432 --dbhost=host --dbname=strapi --dbusername=postgres --dbpassword=mypassword
      - cp server.js database.js  kor-strapi/config/
      - cp -r scripts/ .env kor-strapi/
      - cd kor-strapi
  build:
    commands:
      - yarn build
      - ./scripts/post-build.sh
  post_build:
    commands:

      - mv build/ ../
#reports:
  #report-name-or-arn:
    #files:
      # - location
      # - location
    #base-directory: location
    #discard-paths: yes
    #file-format: JunitXml | CucumberJson
artifacts:
  files:
    - '**/*'
    # - location
  #name: $(date +%Y-%m-%d)
  discard-paths: no
  base-directory: build
#cache:
  #paths:
    # - paths

